version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE: ${POSTGRES_DATABASE}
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      HOST: db
      ALGORITHM: HS256
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "GMT+3"
      PGTZ: "GMT+3"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
